// Code generated by the Lingua Franca compiler from:
// file://Users/shaokai/Documents/projects/lingua-franca/verification/lf-verifier-benchmarks/wip/src/ScheduleTest.lf
#define TARGET_FILES_DIRECTORY "/Users/shaokai/Documents/projects/lingua-franca/verification/lf-verifier-benchmarks/wip/src-gen/ScheduleTest"
#include "include/api/api.h"
#include "core/reactor.h"
#include "core/reactor_common.h"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include "core/port.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
// const char* _lf_default_argv[] = { "dummy", "-o", "50", "msec" };
const char* _lf_default_argv[] = { "dummy" };
void _lf_set_default_command_line_options() {
        default_argc = 1;
        default_argv = _lf_default_argv;
}
// =============== START reactor class Source
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} source_out_t;
typedef struct {
    struct self_base_t base;
    int s;
    source_out_t _lf_out;
    int _lf_out_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
} source_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void sourcereaction_function_0(void* instance_args) {
    source_self_t* self = (source_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    source_out_t* out = &self->_lf_out;
    lf_set(out, self->s++);
    lf_print("Inside source reaction_0");
}
#include "include/api/set_undef.h"
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)_lf_new_reactor(sizeof(source_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = sourcereaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "source_reaction_0";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__t.last = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__t.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    #ifdef FEDERATED
    self->_lf__t.physical_time_of_arrival = NEVER;
    #endif // FEDERATED
    self->_lf__t.is_timer = true;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__t.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    return self;
}
// =============== END reactor class Source
// =============== START reactor class Sink
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} sink_in_t;
typedef struct {
    token_type_t type;
    lf_token_t* token;
    size_t length;
    bool is_present;
    lf_sparse_io_record_t* sparse_record;
    int destination_channel;
    int num_destinations;
    int value;
    #ifdef FEDERATED
    #ifdef FEDERATED_DECENTRALIZED
    tag_t intended_tag;
    #endif
    interval_t physical_time_of_arrival;
    #endif
} sink_in2_t;
typedef struct {
    struct self_base_t base;
    int sum;
    sink_in_t* _lf_in;
    // width of -2 indicates that it is not a multiport.
    int _lf_in_width;
    // Default input (in case it does not get connected)
    sink_in_t _lf_default__in;
    sink_in2_t* _lf_in2;
    // width of -2 indicates that it is not a multiport.
    int _lf_in2_width;
    // Default input (in case it does not get connected)
    sink_in2_t _lf_default__in2;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    reaction_t _lf__reaction_2;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
    trigger_t _lf__in;
    reaction_t* _lf__in_reactions[1];
    #ifdef FEDERATED
    
    #endif // FEDERATED
    trigger_t _lf__in2;
    reaction_t* _lf__in2_reactions[1];
    #ifdef FEDERATED
    
    #endif // FEDERATED
} sink_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/api/set.h"
void sinkreaction_function_0(void* instance_args) {
    sink_self_t* self = (sink_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    self->sum++;
    lf_print("Sum: %d", self->sum);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void sinkreaction_function_1(void* instance_args) {
    sink_self_t* self = (sink_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    sink_in_t* in = self->_lf_in;
    int in_width = self->_lf_in_width; SUPPRESS_UNUSED_WARNING(in_width);
    self->sum += in->value;
    lf_print("Sum: %d", self->sum);
}
#include "include/api/set_undef.h"
#include "include/api/set.h"
void sinkreaction_function_2(void* instance_args) {
    sink_self_t* self = (sink_self_t*)instance_args; SUPPRESS_UNUSED_WARNING(self);
    sink_in2_t* in2 = self->_lf_in2;
    int in2_width = self->_lf_in2_width; SUPPRESS_UNUSED_WARNING(in2_width);
    self->sum += in2->value;
    lf_print("Sum: %d", self->sum);
}
#include "include/api/set_undef.h"
sink_self_t* new_Sink() {
    sink_self_t* self = (sink_self_t*)_lf_new_reactor(sizeof(sink_self_t));
    // Set input by default to an always absent default input.
    self->_lf_in = &self->_lf_default__in;
    // Set input by default to an always absent default input.
    self->_lf_in2 = &self->_lf_default__in2;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = sinkreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "sink_reaction_0";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = sinkreaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "sink_reaction_1";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__reaction_2.number = 2;
    self->_lf__reaction_2.function = sinkreaction_function_2;
    self->_lf__reaction_2.self = self;
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    self->_lf__reaction_2.STP_handler = NULL;
    self->_lf__reaction_2.name = "sink_reaction_2";
    self->_lf__reaction_2.mode = NULL;
    self->_lf__t.last = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__t.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    #ifdef FEDERATED
    self->_lf__t.physical_time_of_arrival = NEVER;
    #endif // FEDERATED
    self->_lf__t.is_timer = true;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__t.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__in.last = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__in.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__in_reactions[0] = &self->_lf__reaction_1;
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    self->_lf__in.number_of_reactions = 1;
    #ifdef FEDERATED
    self->_lf__in.physical_time_of_arrival = NEVER;
    #endif // FEDERATED
    self->_lf__in.tmplt.type.element_size = sizeof(int);
    self->_lf__in2.last = NULL;
    #ifdef FEDERATED_DECENTRALIZED
    self->_lf__in2.intended_tag = (tag_t) { .time = NEVER, .microstep = 0u};
    #endif // FEDERATED_DECENTRALIZED
    self->_lf__in2_reactions[0] = &self->_lf__reaction_2;
    self->_lf__in2.reactions = &self->_lf__in2_reactions[0];
    self->_lf__in2.number_of_reactions = 1;
    #ifdef FEDERATED
    self->_lf__in2.physical_time_of_arrival = NEVER;
    #endif // FEDERATED
    self->_lf__in2.tmplt.type.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Sink
// =============== START reactor class ScheduleTest
typedef struct {
    struct self_base_t base;
} scheduletest_main_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
scheduletest_main_self_t* new_ScheduleTest() {
    scheduletest_main_self_t* self = (scheduletest_main_self_t*)_lf_new_reactor(sizeof(scheduletest_main_self_t));
    return self;
}
// =============== END reactor class ScheduleTest
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[3];
int _lf_timer_triggers_size = 3;
// Array of pointers to startup triggers.
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
	// Initialize tracing
	start_trace("ScheduleTest.lft");
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 2;
    _lf_is_present_fields = (bool**)calloc(2, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(2, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    #ifdef FEDERATED_DECENTRALIZED
    // Create the array that will contain pointers to intended_tag fields to reset on each step.
    _lf_intended_tag_fields_size = 2;
    _lf_intended_tag_fields = (tag_t**)malloc(_lf_intended_tag_fields_size * sizeof(tag_t*));
    
    #endif // FEDERATED_DECENTRALIZED
    int _lf_startup_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_startup_reactions_count);
    int _lf_shutdown_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_shutdown_reactions_count);
    int _lf_reset_reactions_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_reset_reactions_count);
    int _lf_timer_triggers_count = 0;
    SUPPRESS_UNUSED_WARNING(_lf_timer_triggers_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    scheduletest_main_self_t* scheduletest_main_self[1];
    SUPPRESS_UNUSED_WARNING(scheduletest_main_self);
    source_self_t* scheduletest_source_self[1];
    SUPPRESS_UNUSED_WARNING(scheduletest_source_self);
    source_self_t* scheduletest_source2_self[1];
    SUPPRESS_UNUSED_WARNING(scheduletest_source2_self);
    sink_self_t* scheduletest_sink_self[1];
    SUPPRESS_UNUSED_WARNING(scheduletest_sink_self);
    // ***** Start initializing ScheduleTest of class ScheduleTest
    scheduletest_main_self[0] = new_ScheduleTest();
    _lf_register_trace_event(scheduletest_main_self[0], NULL, trace_reactor, "ScheduleTest");
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    {
        // ***** Start initializing ScheduleTest.source of class Source
        scheduletest_source_self[0] = new_Source();
        _lf_register_trace_event(scheduletest_source_self[0], NULL, trace_reactor, "source");
        _lf_register_trace_event(scheduletest_source_self[0], &(scheduletest_source_self[0]->_lf__t), trace_trigger, "source.t");
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        scheduletest_source_self[0]->_lf_out_width = -2;
        { // For scoping
            static int _initial = 0;
            scheduletest_source_self[0]->s = _initial;
        } // End scoping.
        // Initializing timer ScheduleTest.source.t.
        scheduletest_source_self[0]->_lf__t.offset = 0;
        scheduletest_source_self[0]->_lf__t.period = MSEC(10);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &scheduletest_source_self[0]->_lf__t;
        scheduletest_source_self[0]->_lf__t.mode = NULL;
        scheduletest_source_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing ScheduleTest.source
    }
    {
        // ***** Start initializing ScheduleTest.source2 of class Source
        scheduletest_source2_self[0] = new_Source();
        _lf_register_trace_event(scheduletest_source2_self[0], NULL, trace_reactor, "source2");
        _lf_register_trace_event(scheduletest_source2_self[0], &(scheduletest_source2_self[0]->_lf__t), trace_trigger, "source2.t");
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        scheduletest_source2_self[0]->_lf_out_width = -2;
        { // For scoping
            static int _initial = 0;
            scheduletest_source2_self[0]->s = _initial;
        } // End scoping.
        // Initializing timer ScheduleTest.source2.t.
        scheduletest_source2_self[0]->_lf__t.offset = 0;
        scheduletest_source2_self[0]->_lf__t.period = MSEC(10);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &scheduletest_source2_self[0]->_lf__t;
        scheduletest_source2_self[0]->_lf__t.mode = NULL;
        scheduletest_source2_self[0]->_lf__reaction_0.deadline = NEVER;
        //***** End initializing ScheduleTest.source2
    }
    {
        // ***** Start initializing ScheduleTest.sink of class Sink
        scheduletest_sink_self[0] = new_Sink();
        _lf_register_trace_event(scheduletest_sink_self[0], NULL, trace_reactor, "sink");
        _lf_register_trace_event(scheduletest_sink_self[0], &(scheduletest_sink_self[0]->_lf__t), trace_trigger, "sink.t");
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        scheduletest_sink_self[0]->_lf_in_width = -2;
        // width of -2 indicates that it is not a multiport.
        scheduletest_sink_self[0]->_lf_in2_width = -2;
        { // For scoping
            static int _initial = 0;
            scheduletest_sink_self[0]->sum = _initial;
        } // End scoping.
        // Initializing timer ScheduleTest.sink.t.
        scheduletest_sink_self[0]->_lf__t.offset = 0;
        scheduletest_sink_self[0]->_lf__t.period = MSEC(5);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &scheduletest_sink_self[0]->_lf__t;
        scheduletest_sink_self[0]->_lf__t.mode = NULL;
        scheduletest_sink_self[0]->_lf__reaction_0.deadline = NEVER;
        scheduletest_sink_self[0]->_lf__reaction_1.deadline = NEVER;
        scheduletest_sink_self[0]->_lf__reaction_2.deadline = NEVER;
        //***** End initializing ScheduleTest.sink
    }
    //***** End initializing ScheduleTest
    // **** Start deferred initialize for ScheduleTest
    {
        // **** Start deferred initialize for ScheduleTest.source
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ScheduleTest.source.
            scheduletest_source_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            scheduletest_source_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &scheduletest_source_self[0]->base.allocations);
            scheduletest_source_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &scheduletest_source_self[0]->base.allocations);
            scheduletest_source_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &scheduletest_source_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    scheduletest_source_self[0]->_lf__reaction_0.output_produced[count++] = &scheduletest_source_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of ScheduleTest.source
        }
        // **** End of deferred initialize for ScheduleTest.source
        // **** Start deferred initialize for ScheduleTest.source2
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ScheduleTest.source2.
            scheduletest_source2_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            scheduletest_source2_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &scheduletest_source2_self[0]->base.allocations);
            scheduletest_source2_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &scheduletest_source2_self[0]->base.allocations);
            scheduletest_source2_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &scheduletest_source2_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    scheduletest_source2_self[0]->_lf__reaction_0.output_produced[count++] = &scheduletest_source2_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of ScheduleTest.source2
        }
        // **** End of deferred initialize for ScheduleTest.source2
        // **** Start deferred initialize for ScheduleTest.sink
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of ScheduleTest.sink.
            scheduletest_sink_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ScheduleTest.sink
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ScheduleTest.sink.
            scheduletest_sink_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of ScheduleTest.sink
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of ScheduleTest.sink.
            scheduletest_sink_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 2 of ScheduleTest.sink
        }
        // **** End of deferred initialize for ScheduleTest.sink
    }
    // **** End of deferred initialize for ScheduleTest
    // **** Start non-nested deferred initialize for ScheduleTest
    // **** Start non-nested deferred initialize for ScheduleTest.source
    // For reference counting, set num_destinations for port ScheduleTest.source.out.
    // Iterate over range ScheduleTest.source.out(0,1)->[ScheduleTest.sink.in(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        scheduletest_source_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ScheduleTest.source.out(0,1)->[ScheduleTest.sink.in(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of ScheduleTest.source triggers 1 downstream reactions
            // through port ScheduleTest.source.out.
            scheduletest_source_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of ScheduleTest.source, allocate an
            // array of trigger pointers for downstream reactions through port ScheduleTest.source.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &scheduletest_source_self[src_runtime]->base.allocations); 
            scheduletest_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ScheduleTest.source.out(0,1)->[ScheduleTest.sink.in(0,1)] and ScheduleTest.sink.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ScheduleTest.sink.in(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ScheduleTest.sink.in's trigger struct.
                scheduletest_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &scheduletest_sink_self[dst_runtime]->_lf__in;
            }
        }
    }
    // **** End of non-nested deferred initialize for ScheduleTest.source
    // **** Start non-nested deferred initialize for ScheduleTest.source2
    // For reference counting, set num_destinations for port ScheduleTest.source2.out.
    // Iterate over range ScheduleTest.source2.out(0,1)->[ScheduleTest.sink.in2(0,1)].
    {
        int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
        int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
        int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
        scheduletest_source2_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range ScheduleTest.source2.out(0,1)->[ScheduleTest.sink.in2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            // Reaction 0 of ScheduleTest.source2 triggers 1 downstream reactions
            // through port ScheduleTest.source2.out.
            scheduletest_source2_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of ScheduleTest.source2, allocate an
            // array of trigger pointers for downstream reactions through port ScheduleTest.source2.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &scheduletest_source2_self[src_runtime]->base.allocations); 
            scheduletest_source2_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges ScheduleTest.source2.out(0,1)->[ScheduleTest.sink.in2(0,1)] and ScheduleTest.sink.in2(0,1).
        {
            int src_runtime = 0; // Runtime index.
            SUPPRESS_UNUSED_WARNING(src_runtime);
            int src_channel = 0; // Channel index.
            SUPPRESS_UNUSED_WARNING(src_channel);
            int src_bank = 0; // Bank index.
            SUPPRESS_UNUSED_WARNING(src_bank);
            // Iterate over range ScheduleTest.sink.in2(0,1).
            {
                int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Point to destination port ScheduleTest.sink.in2's trigger struct.
                scheduletest_source2_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &scheduletest_sink_self[dst_runtime]->_lf__in2;
            }
        }
    }
    // **** End of non-nested deferred initialize for ScheduleTest.source2
    // **** Start non-nested deferred initialize for ScheduleTest.sink
    // **** End of non-nested deferred initialize for ScheduleTest.sink
    // **** End of non-nested deferred initialize for ScheduleTest
    // Connect inputs and outputs for reactor ScheduleTest.
    // Connect inputs and outputs for reactor ScheduleTest.source.
    // Connect ScheduleTest.source.out(0,1)->[ScheduleTest.sink.in(0,1)] to port ScheduleTest.sink.in(0,1)
    // Iterate over ranges ScheduleTest.source.out(0,1)->[ScheduleTest.sink.in(0,1)] and ScheduleTest.sink.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ScheduleTest.sink.in(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            scheduletest_sink_self[dst_runtime]->_lf_in = (sink_in_t*)&scheduletest_source_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor ScheduleTest.source2.
    // Connect ScheduleTest.source2.out(0,1)->[ScheduleTest.sink.in2(0,1)] to port ScheduleTest.sink.in2(0,1)
    // Iterate over ranges ScheduleTest.source2.out(0,1)->[ScheduleTest.sink.in2(0,1)] and ScheduleTest.sink.in2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ScheduleTest.sink.in2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            scheduletest_sink_self[dst_runtime]->_lf_in2 = (sink_in2_t*)&scheduletest_source2_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor ScheduleTest.sink.
    {
    }
    {
    }
    {
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port ScheduleTest.source.out to array of is_present fields.
            _lf_is_present_fields[0 + count] = &scheduletest_source_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ScheduleTest.source.out to array of intended_tag fields.
            _lf_intended_tag_fields[0 + count] = &scheduletest_source_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port ScheduleTest.source2.out to array of is_present fields.
            _lf_is_present_fields[1 + count] = &scheduletest_source2_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port ScheduleTest.source2.out to array of intended_tag fields.
            _lf_intended_tag_fields[1 + count] = &scheduletest_source2_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    // Set reaction priorities for ReactorInstance ScheduleTest
    {
        // Set reaction priorities for ReactorInstance ScheduleTest.source
        {
            scheduletest_source_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            scheduletest_source_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        }
        // Set reaction priorities for ReactorInstance ScheduleTest.source2
        {
            scheduletest_source2_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            scheduletest_source2_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
        }
        // Set reaction priorities for ReactorInstance ScheduleTest.sink
        {
            scheduletest_sink_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            scheduletest_sink_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            scheduletest_sink_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            scheduletest_sink_self[0]->_lf__reaction_1.index = 0xffffffffffff0001LL;
            scheduletest_sink_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            scheduletest_sink_self[0]->_lf__reaction_2.index = 0xffffffffffff0002LL;
        }
    }

    struct self_base_t** _lf_reactor_self_instances = (struct self_base_t**) calloc(3, sizeof(reaction_t*));
    _lf_reactor_self_instances[0] = &(scheduletest_source_self[0]->base);
    _lf_reactor_self_instances[1] = &(scheduletest_source2_self[0]->base);
    _lf_reactor_self_instances[2] = &(scheduletest_sink_self[0]->base);
    // FIXME: Why can't we put the pointer array on the stack?
    /*
    struct self_base_t* _lf_reactor_self_instances[3] = {
        &(scheduletest_source_self[0]->base),
        &(scheduletest_source2_self[0]->base),
        &(scheduletest_sink_self[0]->base)
    };
    */

    reaction_t** _lf_reaction_instances = (reaction_t**) calloc(5, sizeof(reaction_t*));
    _lf_reaction_instances[0] = &(scheduletest_source_self[0]->_lf__reaction_0);
    _lf_reaction_instances[1] = &(scheduletest_source2_self[0]->_lf__reaction_0);
    _lf_reaction_instances[2] = &(scheduletest_sink_self[0]->_lf__reaction_0);
    _lf_reaction_instances[3] = &(scheduletest_sink_self[0]->_lf__reaction_1);
    _lf_reaction_instances[4] = &(scheduletest_sink_self[0]->_lf__reaction_2);

    bool reactor_reached_stop_tag[3] = { false };

    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {3, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
        .num_reactions_per_level = &num_reactions_per_level[0],
        .num_reactions_per_level_size = (size_t) 3,
        .reactor_self_instances = &_lf_reactor_self_instances[0],
        .num_reactor_self_instances = 3,
        .reaction_instances = _lf_reaction_instances,
        .reactor_reached_stop_tag = &reactor_reached_stop_tag[0],
    };
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble();
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void _lf_trigger_startup_reactions() {}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED
}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
#ifndef FEDERATED
void terminate_execution() {}
#endif
